#!/bin/zsh
set -euo pipefail

script_dir="$(cd "$(dirname "$0")" && pwd -P)"
project_dir="$(cd "$script_dir/.." && pwd -P)"
template_dir="$project_dir/launchd/templates"
target_dir="${LAUNCHD_TARGET_DIR:-$HOME/Library/LaunchAgents}"
runtime_dir="${DAILY_TECH_LOG_DIR:-$HOME/Library/Logs/daily-tech-site}"
alias_dir="${DAILY_TECH_SITE_ALIAS:-$HOME/.daily-tech-site}"
wiki_alias_dir="${DAILY_TECH_WIKI_ALIAS:-$HOME/.daily-tech-site-wiki}"
support_dir="${DAILY_TECH_SUPPORT_DIR:-$HOME/Library/Application Support/daily-tech-site}"
support_qmd_wrapper="$support_dir/dailytech_qmd_refresh.sh"
support_runtime_dir="$support_dir/runtime"
support_site_env="$support_dir/site.env"
support_tunnel_env="$support_dir/cloudflare-tunnel.env"
support_site_wrapper="$support_dir/dailytech_site_web.sh"
support_refresh_wrapper="$support_dir/dailytech_refresh_check.sh"
support_tunnel_wrapper="$support_dir/dailytech_tunnel.sh"
uid="$(id -u)"
env_file="$project_dir/.env"
disabled_refresh_plists=(
  "$target_dir/com.dailytech.site.refresh.afternoon.plist"
  "$target_dir/com.dailytech.site.refresh.evening.plist"
)

if [[ -f "$env_file" ]]; then
  set -a
  source "$env_file"
  set +a
fi

slot_enabled() {
  local slot="$1"
  local enabled_slots=",${DAILY_COLLECTION_SLOTS:-morning},"
  [[ "$enabled_slots" == *",$slot,"* ]]
}

mkdir -p "$target_dir"
mkdir -p "$runtime_dir"
mkdir -p "$support_dir"
ln -sfn "$project_dir" "$alias_dir"

if [[ -n "${WIKI_SOURCE_DIR:-}" ]]; then
  ln -sfn "$WIKI_SOURCE_DIR" "$wiki_alias_dir"
fi

cp "$script_dir/run-qmd-refresh.sh" "$support_qmd_wrapper"
chmod +x "$support_qmd_wrapper"

if [[ ! -f "$project_dir/.env" && ! -f "$support_site_env" ]]; then
  umask 077
  token="$(/usr/bin/openssl rand -hex 24)"
  {
    printf '# Generated by scripts/install-launchd.sh. Keep this file private.\n'
    printf 'MAINTENANCE_TOKEN=%s\n' "$token"
  } > "$support_site_env"
fi
chmod 600 "$support_site_env" 2>/dev/null || true
if [[ -f "$project_dir/.env.tunnel" ]]; then
  cp "$project_dir/.env.tunnel" "$support_tunnel_env"
  chmod 600 "$support_tunnel_env"
fi

mkdir -p "$support_runtime_dir"
/usr/bin/rsync -a --delete \
  --exclude '.git' \
  --exclude 'node_modules' \
  --exclude '.cache' \
  "$project_dir/" "$support_runtime_dir/"

escape_sed() {
  printf '%s' "$1" | sed 's/[\/&]/\\&/g'
}

render_template() {
  local source_plist="$1"
  local target_plist="$2"
  local project_escaped log_escaped support_escaped
  project_escaped="$(escape_sed "$project_dir")"
  log_escaped="$(escape_sed "$runtime_dir")"
  support_escaped="$(escape_sed "$support_dir")"
  sed \
    -e "s/__PROJECT_DIR__/$project_escaped/g" \
    -e "s/__LOG_DIR__/$log_escaped/g" \
    -e "s/__SUPPORT_DIR__/$support_escaped/g" \
    "$source_plist" > "$target_plist"
}

cat > "$support_site_wrapper" <<'SH'
#!/bin/zsh
set -euo pipefail

support_dir="${DAILY_TECH_SUPPORT_DIR:-$HOME/Library/Application Support/daily-tech-site}"
runtime_dir="$support_dir/runtime"

export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

if [[ -f "$runtime_dir/.env" ]]; then
  set -a
  source "$runtime_dir/.env"
  set +a
fi
if [[ -f "$support_dir/site.env" ]]; then
  set -a
  source "$support_dir/site.env"
  set +a
fi

export CACHE_DIR="${CACHE_DIR:-$support_dir/cache}"
export REPORTS_INDEX_FILE="${REPORTS_INDEX_FILE:-$support_dir/cache/snapshots.json}"
export LATEST_INDEX_FILE="${LATEST_INDEX_FILE:-$support_dir/cache/latest.json}"
export DETAIL_CACHE_DIR="${DETAIL_CACHE_DIR:-$support_dir/cache/snapshot-details}"
export OPS_STATUS_FILE="${OPS_STATUS_FILE:-$support_dir/cache/ops-status.json}"
export REFRESH_STATE_FILE="${REFRESH_STATE_FILE:-$support_dir/cache/refresh-state.json}"

if [[ -z "${MAINTENANCE_TOKEN:-}" ]]; then
  echo "MAINTENANCE_TOKEN is required for launchd site service." >&2
  exit 1
fi

cd "$runtime_dir"
exec /opt/homebrew/bin/node server.js
SH
chmod +x "$support_site_wrapper"

cat > "$support_refresh_wrapper" <<'SH'
#!/bin/zsh
set -euo pipefail

slot="${1:?slot required}"
support_dir="${DAILY_TECH_SUPPORT_DIR:-$HOME/Library/Application Support/daily-tech-site}"
runtime_dir="$support_dir/runtime"

export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

if [[ -f "$runtime_dir/.env" ]]; then
  set -a
  source "$runtime_dir/.env"
  set +a
fi
if [[ -f "$support_dir/site.env" ]]; then
  set -a
  source "$support_dir/site.env"
  set +a
fi

export CACHE_DIR="${CACHE_DIR:-$support_dir/cache}"
export REPORTS_INDEX_FILE="${REPORTS_INDEX_FILE:-$support_dir/cache/snapshots.json}"
export LATEST_INDEX_FILE="${LATEST_INDEX_FILE:-$support_dir/cache/latest.json}"
export DETAIL_CACHE_DIR="${DETAIL_CACHE_DIR:-$support_dir/cache/snapshot-details}"
export OPS_STATUS_FILE="${OPS_STATUS_FILE:-$support_dir/cache/ops-status.json}"
export REFRESH_STATE_FILE="${REFRESH_STATE_FILE:-$support_dir/cache/refresh-state.json}"

cd "$runtime_dir"
exec /opt/homebrew/bin/node scripts/check-refresh.js --slot "$slot"
SH
chmod +x "$support_refresh_wrapper"

cat > "$support_tunnel_wrapper" <<'SH'
#!/bin/zsh
set -eu

support_dir="${DAILY_TECH_SUPPORT_DIR:-$HOME/Library/Application Support/daily-tech-site}"
env_file="$support_dir/cloudflare-tunnel.env"

if [[ -f "$env_file" ]]; then
  source "$env_file"
fi

if [[ -z "${CLOUDFLARED_TUNNEL_TOKEN:-}" ]]; then
  echo "CLOUDFLARED_TUNNEL_TOKEN is missing in $env_file" >&2
  exit 1
fi

export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
export TUNNEL_TOKEN="$CLOUDFLARED_TUNNEL_TOKEN"
export NO_PROXY="${NO_PROXY:-127.0.0.1,localhost,::1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16}"
unset CLOUDFLARED_TUNNEL_TOKEN HTTPS_PROXY HTTP_PROXY ALL_PROXY

edge_args=()
if [[ -n "${CLOUDFLARED_EDGE_ARGS:-}" ]]; then
  # shellcheck disable=SC2206
  edge_args=(${=CLOUDFLARED_EDGE_ARGS})
else
  edge_args=(
    --edge 198.41.192.27:7844
    --edge 198.41.192.47:7844
    --edge 198.41.200.73:7844
    --edge 198.41.200.113:7844
  )
fi

exec /opt/homebrew/bin/cloudflared tunnel \
  --no-autoupdate \
  --metrics 127.0.0.1:20241 \
  --protocol http2 \
  "${edge_args[@]}" \
  run
SH
chmod 700 "$support_tunnel_wrapper"

for disabled_plist in "${disabled_refresh_plists[@]}"; do
  launchctl bootout "gui/$uid" "$disabled_plist" >/dev/null 2>&1 || true
  rm -f "$disabled_plist"
done

for source_plist in "$template_dir"/*.plist; do
  file_name="$(basename "$source_plist")"
  if [[ "$file_name" == "com.dailytech.site.refresh.afternoon.plist" && "${INSTALL_AFTERNOON_REFRESH:-0}" != "1" ]] && ! slot_enabled "afternoon"; then
    continue
  fi
  if [[ "$file_name" == "com.dailytech.site.refresh.evening.plist" && "${INSTALL_EVENING_REFRESH:-0}" != "1" ]] && ! slot_enabled "evening"; then
    continue
  fi
  if [[ "$file_name" == "com.dailytech.site.tunnel.plist" && ! -f "$project_dir/.env.tunnel" ]]; then
    continue
  fi
  if [[ "$file_name" == "com.dailytech.qmd.refresh.plist" && -z "${WIKI_SOURCE_DIR:-}" ]]; then
    continue
  fi

  target_plist="$target_dir/$file_name"
  render_template "$source_plist" "$target_plist"

  label="${file_name%.plist}"
  launchctl bootout "gui/$uid" "$target_plist" >/dev/null 2>&1 || true
  launchctl bootstrap "gui/$uid" "$target_plist"
done

launchctl kickstart -k "gui/$uid/com.dailytech.site.web" >/dev/null 2>&1 || true

printf "launchd agents installed in %s\n" "$target_dir"

if [[ ! -f "$project_dir/.env.tunnel" ]]; then
  printf "cloudflare tunnel skipped: create %s/.env.tunnel first\n" "$project_dir"
fi

if [[ -z "${WIKI_SOURCE_DIR:-}" ]]; then
  printf "qmd refresh skipped: set WIKI_SOURCE_DIR in .env to enable it\n"
fi
